// This file is automatically generated.

interface CssExports {
  'Slider': string;
  'input': string;
  'thumb_autohide': string;
  'tip': string;
  'tip_body': string;
  'track': string;
}

declare var cssExports: CssExports;
export = cssExports;
