// This file is automatically generated.

interface CssExports {
  'AutBar': string;
  'actions': string;
  'container': string;
  'hiddenFields': string;
}

declare var cssExports: CssExports;
export = cssExports;
