// This file is automatically generated.

interface CssExports {
  'AutBar': string;
  'checking_row': string;
  'container': string;
  'row': string;
  'subtitle': string;
}

declare var cssExports: CssExports;
export = cssExports;
