// This file is automatically generated.

interface CssExports {
  'AudioActions': string;
  'AudioContainer': string;
  'AudioPlayer': string;
  'AudioTrack': string;
  'audio_file_input': string;
  'buttons': string;
  'control_bar': string;
  'data': string;
  'header': string;
  'progress': string;
  'selected': string;
  'track_duration': string;
  'track_info': string;
  'volume': string;
}

declare var cssExports: CssExports;
export = cssExports;
