// This file is automatically generated.

interface CssExports {
  'SearchContainer': string;
  'search_string': string;
  'users_container': string;
}

declare var cssExports: CssExports;
export = cssExports;
