// This file is automatically generated.

interface CssExports {
  'UserPage': string;
  'avatar': string;
  'other': string;
  'userData': string;
  'userName': string;
  'userPropertie': string;
}

declare var cssExports: CssExports;
export = cssExports;
