// This file is automatically generated.

interface CssExports {
  'UserPage': string;
  'avatar': string;
  'fileform': string;
  'header': string;
  'inputAvatar': string;
  'left_column': string;
  'right_column': string;
  'selectedAvatarText': string;
  'user_data': string;
  'user_data_header': string;
  'user_data_table': string;
}

declare var cssExports: CssExports;
export = cssExports;
