// This file is automatically generated.

interface CssExports {
  'Toast': string;
  'ToastBody': string;
  'ToastContainer': string;
  'app-body': string;
  'app_logo': string;
  'vertical_container': string;
}

declare var cssExports: CssExports;
export = cssExports;
