// This file is automatically generated.

interface CssExports {
  'Divider': string;
  'large-space': string;
  'medium-space': string;
  'small-space': string;
}

declare var cssExports: CssExports;
export = cssExports;
