// This file is automatically generated.

interface CssExports {
  'Divider': string;
  'large-indent': string;
  'medium-indent': string;
  'small-indent': string;
}

declare var cssExports: CssExports;
export = cssExports;
