// This file is automatically generated.

interface CssExports {
  'DropdownContainer': string;
  'DropdownItem': string;
  'DropdownMenu': string;
  'arrow': string;
  'left_placement': string;
  'opened': string;
  'right_placement': string;
}

declare var cssExports: CssExports;
export = cssExports;
