// This file is automatically generated.

interface CssExports {
  'Select': string;
  'border': string;
  'control': string;
  'label': string;
  'label-focus': string;
  'opened': string;
  'option': string;
  'option_container': string;
  'outline': string;
  'selected': string;
  'value': string;
}

declare var cssExports: CssExports;
export = cssExports;
