// This file is automatically generated.

interface CssExports {
  'InputField': string;
  'border': string;
  'eye': string;
  'eye-slash': string;
  'highlighting': string;
  'input': string;
  'input-container': string;
  'label': string;
  'label-focus': string;
  'outline': string;
}

declare var cssExports: CssExports;
export = cssExports;
