// This file is automatically generated.

interface CssExports {
  'Dialog': string;
  'avatar': string;
  'border_bottom': string;
  'label-new_message': string;
  'label_flashing': string;
  'online': string;
  'right_column': string;
  'user_data': string;
  'user_name': string;
  'user_status': string;
}

declare var cssExports: CssExports;
export = cssExports;
