// This file is automatically generated.

interface CssExports {
  'DialogList': string;
  'dialog_column': string;
  'dialog_list': string;
  'header': string;
}

declare var cssExports: CssExports;
export = cssExports;
