// This file is automatically generated.

interface CssExports {
  'Message': string;
  'avatar': string;
  'content': string;
  'my': string;
  'timestamp': string;
}

declare var cssExports: CssExports;
export = cssExports;
