// This file is automatically generated.

interface CssExports {
  'StepDivider': string;
  'Stepper': string;
  'StepperItem': string;
  'completed': string;
  'selected': string;
}

declare var cssExports: CssExports;
export = cssExports;
