// This file is automatically generated.

interface CssExports {
  'TextArea': string;
  'border': string;
  'field_name': string;
  'text_field': string;
}

declare var cssExports: CssExports;
export = cssExports;
