// This file is automatically generated.

interface CssExports {
  'TextArea': string;
  'area': string;
  'border': string;
  'fieldName': string;
}

declare var cssExports: CssExports;
export = cssExports;
