// This file is automatically generated.

interface CssExports {
  'Note': string;
  'Notes': string;
  'container': string;
  'content': string;
  'header': string;
  'name': string;
  'plus': string;
}

declare var cssExports: CssExports;
export = cssExports;
