// This file is automatically generated.

interface CssExports {
  'IconButton': string;
  'icon': string;
  'large': string;
  'medium': string;
  'small': string;
  'very_large': string;
  'very_small': string;
}

declare var cssExports: CssExports;
export = cssExports;
