// This file is automatically generated.

interface CssExports {
  'UserPrew': string;
  'avatar': string;
  'residence_place': string;
  'user_data': string;
}

declare var cssExports: CssExports;
export = cssExports;
