// This file is automatically generated.

interface CssExports {
  'ModalHeader': string;
  'close-button': string;
  'error': string;
  'info': string;
  'primary': string;
  'secondary': string;
  'success': string;
  'warning': string;
}

declare var cssExports: CssExports;
export = cssExports;
