// This file is automatically generated.

interface CssExports {
  'ModalWindow': string;
  'large': string;
  'medium': string;
  'opened': string;
  'small': string;
}

declare var cssExports: CssExports;
export = cssExports;
