// This file is automatically generated.

interface CssExports {
  'ModalBody': string;
  'ModalFooter': string;
  'ModalHeader': string;
  'ModalWindow': string;
  'error': string;
  'info': string;
  'large': string;
  'medium': string;
  'opened': string;
  'primary': string;
  'secondary': string;
  'small': string;
  'success': string;
  'warning': string;
}

declare var cssExports: CssExports;
export = cssExports;
