// This file is automatically generated.

interface CssExports {
  'MenuIcon': string;
  'MenuItem': string;
  'SideMenu': string;
  'opened': string;
}

declare var cssExports: CssExports;
export = cssExports;
