// This file is automatically generated.

interface CssExports {
  'Loading': string;
  'circle': string;
  'first': string;
  'firstMoving': string;
  'fourth': string;
  'fourthMoving': string;
  'second': string;
  'secondMoving': string;
  'third': string;
  'thirdMoving': string;
}

declare var cssExports: CssExports;
export = cssExports;
