// This file is automatically generated.

interface CssExports {
  'Tooltip': string;
  'bottom': string;
  'left': string;
  'right': string;
  'show_tip': string;
  'top': string;
}

declare var cssExports: CssExports;
export = cssExports;
