// This file is automatically generated.

interface CssExports {
  'DatePicker': string;
  'actions': string;
  'cell': string;
  'disabled': string;
  'header': string;
  'opened': string;
  'selected': string;
  'selector': string;
  'selectors': string;
}

declare var cssExports: CssExports;
export = cssExports;
