// This file is automatically generated.

interface CssExports {
  'Bookmarks': string;
  'bookmarks_container': string;
  'header': string;
}

declare var cssExports: CssExports;
export = cssExports;
