// This file is automatically generated.

interface CssExports {
  'Bookmark': string;
  'buttons': string;
  'data': string;
  'icon': string;
  'name': string;
  'plus': string;
  'url': string;
}

declare var cssExports: CssExports;
export = cssExports;
