// This file is automatically generated.

interface CssExports {
  'Alert': string;
  'badge': string;
  'close-button': string;
  'content': string;
  'error': string;
  'error-close': string;
  'info': string;
  'info-close': string;
  'open': string;
  'success': string;
  'success-close': string;
  'warning': string;
  'warning-close': string;
}

declare var cssExports: CssExports;
export = cssExports;
